vich_uploader:
    db_driver: orm

    mappings:
        thumbnails:
            uri_prefix: 'uploads/avatars'
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            
        videos:
            uri_prefix: 'uploads/avatars'
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'            
