vich_uploader:
    db_driver: orm

    mappings:
        thumbnails:
            uri_prefix: 'uploads/avatars'
            upload_destination: 'C:\Users\ASUS\Desktop\monpfe\public\uploads\avatars'
            
        videos:
            uri_prefix: 'uploads/avatars'
            upload_destination: 'C:\Users\ASUS\Desktop\monpfe\public\uploads\avatars'            
